// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-67KrgNh9-qO9VbQZfxmuJlKqRF36RmY',
    appId: '1:875392173577:web:e0c87e5028d28c112d5ad8',
    messagingSenderId: '875392173577',
    projectId: 'chat-app-73fc3',
    authDomain: 'chat-app-73fc3.firebaseapp.com',
    storageBucket: 'chat-app-73fc3.appspot.com',
    measurementId: 'G-7KN8LWDGMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEJdcgaasd09t5FO_AXextNTqJhXhF9Yc',
    appId: '1:875392173577:android:f8220cd5bf0261aa2d5ad8',
    messagingSenderId: '875392173577',
    projectId: 'chat-app-73fc3',
    storageBucket: 'chat-app-73fc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfoAXy0LiXFPJDbLTyQZIiYHMDrcCDZOA',
    appId: '1:875392173577:ios:e73b768ad5630b322d5ad8',
    messagingSenderId: '875392173577',
    projectId: 'chat-app-73fc3',
    storageBucket: 'chat-app-73fc3.appspot.com',
    iosClientId: '875392173577-cnoh0r739jpg2a9mgo0117blrcd8q51q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfoAXy0LiXFPJDbLTyQZIiYHMDrcCDZOA',
    appId: '1:875392173577:ios:e73b768ad5630b322d5ad8',
    messagingSenderId: '875392173577',
    projectId: 'chat-app-73fc3',
    storageBucket: 'chat-app-73fc3.appspot.com',
    iosClientId: '875392173577-cnoh0r739jpg2a9mgo0117blrcd8q51q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppWithFirebase',
  );
}
